# Generated by Django 5.2.7 on 2025-12-18 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_result_is_correct_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('failed', 'Failed'), ('done', 'Done')], default='queued', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('logs', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='python', max_length=32)),
                ('vuln_type', models.CharField(default='sqli', max_length=64)),
                ('difficulty', models.CharField(default='easy', max_length=16)),
                ('artifact', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='api.generationrequest')),
            ],
        ),
    ]
