# Generated by Django 5.2.7 on 2026-02-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_result_generated_challenge_alter_result_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedchallenge',
            name='is_pooled',
            field=models.BooleanField(default=False),
        ),
    ]
